#Entrada principal del Sistema
inicio:
    path: /
    defaults:
        _controller: ArquitecturaBaseBundle:Base:inicio

arquitectura_base:
    resource: "@ArquitecturaBaseBundle/Resources/config/arquitecturabase.yml"
    prefix:   /base

administracion:
    resource: "@ArquitecturaBaseBundle/Resources/config/administracion.yml"
    prefix:   /administracion


login:
    path: /login
    defaults:
        _controller: ArquitecturaBaseBundle:Autenticacion:login
logout:
    path: /logout
