<?php

namespace ArquitecturaBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IconoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IconoRepository extends EntityRepository
{
}
