<?php

namespace ArquitecturaBaseBundle\Repository;

use ArquitecturaBaseBundle\Entity\Rol;
use Doctrine\ORM\EntityRepository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
    /**
     * @return Rol
     * @throws \Exception
     */
    public function buscarRolPrincipal(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('rol')
            ->from('ArquitecturaBaseBundle:Rol','rol')
            ->andWhere($qb->expr()->isNull('rol.rolPadre'))
        ;
        try{
            $rol = $qb->getQuery()->getSingleResult();
            return $rol;
        }catch(\Exception $e){
            throw new \Exception("No existe un único rol padre de la jerarquía de roles. Verifique a su administrador");
        }
    }
}
