<?php

namespace ArquitecturaBaseBundle\Repository;

use ArquitecturaBaseBundle\Utiles\Util;
use \Doctrine\ORM\EntityRepository;
/**
 * TrazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrazaRepository extends EntityRepository
{
    public function BuscarTraza($user, $count, $inicio, $fin, $sort, $order, $search) {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('COUNT(traza)')
            ->from('ArquitecturaBaseBundle:Traza', 'traza');

        //buscar parámetros
        $fieldsName = array(
            'traza.fecha',
            'traza.usuario',
            'traza.ip',
            'traza.accion'
        );
        Util::bindSearch($qb, $search, $fieldsName);

        if (!is_null($count)) {
            $result = $qb->getQuery()->getSingleScalarResult();
            return $result;
        } else {
            $sortBy = 'a.index';
            $sortBy = $sort == 'getIndexGrid' ? 'a.index': $sortBy;
            $sortBy = $sort == 'getNameToStringGrid' ? 'a.name': $sortBy;
            $sortBy = $sort == 'getDescriptionToStringGrid' ? 'a.description': $sortBy;

            $qb->select('traza');
            $qb->orderBy($sortBy, $order)
                ->setFirstResult($inicio);

            if($fin != -1) {
                $qb->setMaxResults($fin);
            }

            return $qb->getQuery()->getResult();
        }
    }

}
