<?php

namespace ArquitecturaBaseBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository
{
    public function listarExcepto($idusuario){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('ArquitecturaBaseBundle:Usuario','u')
            ->where($qb->expr()->neq('u.id',':prmIdUsuario'))
            ->setParameter('prmIdUsuario',$idusuario)
        ;
        return $qb->getQuery()->getResult();
    }

    public function buscarUsuariosSinPersona(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u.id')
            ->from('ArquitecturaBaseBundle:Usuario','u')
            ->innerJoin('u.persona','p')
        ;
        $usuarios = $qb->getQuery()->getArrayResult();

        if (count($usuarios) == 0){
            $qb = $this->getEntityManager()->createQueryBuilder();
            $qb->select('u')
                ->from('ArquitecturaBaseBundle:Usuario','u')
            ;
            return $qb;
        }

        $qb2 = $this->getEntityManager()->createQueryBuilder();
        $qb2->select('u')
            ->from('ArquitecturaBaseBundle:Usuario','u')
            ->andWhere($qb2->expr()->notIn('u.id',':prmArrayUsuarios'))
            ->setParameter('prmArrayUsuarios',$usuarios)
        ;
        return $qb2;
    }

    public function qbUsuario()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u')
            ->from('ArquitecturaBaseBundle:Usuario');
            return $qb->getQuery();

    }
}
