inicio_admin:
    path: /inicio
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:index
        etiqueta: 'Inicio Administracion'
        mostrarEnMenu: true

#Importaciones
usuarios:
    resource: "@ArquitecturaBaseBundle/Resources/config/usuario.yml"
    prefix: /usuario

roles:
    resource: "@ArquitecturaBaseBundle/Resources/config/roles.yml"
    prefix: /rol

menu:
    resource: "@ArquitecturaBaseBundle/Resources/config/menu.yml"
    prefix: /menu

plantilla:
    resource: "@ArquitecturaBaseBundle/Resources/config/plantilla.yml"
    prefix: /plantilla

trazas:
    resource: "@ArquitecturaBaseBundle/Resources/config/trazas.yml"
    prefix: /trazas

concesiones:
    resource: "@ArquitecturaBaseBundle/Resources/config/concesiones.yml"
    prefix: /concesion