arquitectura_base_homepage:
    path:     /
    defaults:
        _controller: ArquitecturaBaseBundle:Default:index
        etiqueta: 'Inicio'
        mostrarEnMenu: true

perfil:
    path: /perfil
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:mostrarPerfil
        etiqueta: 'Perfil'
        mostrarEnMenu: true

salir:
    path: /salir
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:salir

prueba:
    path: /prueba
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:prueba
        mostrarEnMenu: false
        etiqueta: 'Prueba'

#Importaciones
administracion:
    resource: "@ArquitecturaBaseBundle/Resources/config/administracion.yml"
    prefix: /administracion