gestionar_concesiones_inicio:
    path: /inicio
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:gestionarConcesiones
        etiqueta: 'Listar menus sin concesiones'
        mostrarEnMenu: true

crear_concesion:
    path: /crear/{idmenu}
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:crearConcesion
        idmenu: -1
        etiqueta: 'Agregar nueva concesión'
        mostrarEnMenu: true

gestionar_concesion_rol:
    path: /gestionar/{idrol}
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:gestionar
        idrol: -1

concesiones_load_ajax:
    path: /load_ajax/{idrol}
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:loadAjax
        idrol : null
#AJAX
concesiones_modificar:
    path: /modificar
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:modificar

#AJAX
cargar_usuarios_ajax:
    path: /cargarUsuariosAjax
    defaults:
        _controller: ArquitecturaBaseBundle:Concesion:cargarUsuariosAjax