gestionar_menus:
    path: /gestionar
    defaults:
        _controller: ArquitecturaBaseBundle:Menu:listarMenus
        etiqueta: "Listar Menus"
        mostrarEnMenu: true
        padre:
            - 'arquitectura_base_homepage'

cargar_menus_ajax:
    path: /listarajax
    defaults:
        _controller: ArquitecturaBaseBundle:Menu:cargarMenusAjax

crear_menu:
    path: /crear
    defaults:
        _controller: ArquitecturaBaseBundle:Menu:crearMenu
        etiqueta: 'Crear Menu'
        mostrarEnMenu: true
