crear_rol:
    path: /crear
    defaults:
        _controller: ArquitecturaBaseBundle:Rol:crearRol
        etiqueta: 'Crear nuevo rol'
        mostrarEnMenu: true

listar_rol:
    path: /listar
    defaults:
        _controller: ArquitecturaBaseBundle:Rol:listarRoles
        etiqueta: 'Listar rol'
        mostrarEnMenu: true
#AJAX
generar_arbol_roles:
    path: /arbol
    defaults:
        _controller: ArquitecturaBaseBundle:Rol:buscarRolesHijosDeRol
#AJAX
arbol_nodo_informacion:
    path: /nodo/informacion
    defaults:
        _controller: ArquitecturaBaseBundle:Rol:informacionNodoRol

load_ajax_roles:
    path: /roles_load_ajax
    defaults:
        _controller: ArquitecturaBaseBundle:Rol:loadAjax