usuario_agregar:
    path: /agregar
    defaults:
        _controller: ArquitecturaBaseBundle:Usuario:crearUsuario
        etiqueta: 'Crear un usuario'
        mostrarEnMenu: true

usuario_modificar:
    path: /modificar/{idusuario}
    defaults:
        _controller: ArquitecturaBaseBundle:Usuario:modificarUsuario

usuario_listar:
    path: /listar
    defaults:
        _controller: ArquitecturaBaseBundle:Usuario:listarUsuarios
        etiqueta: 'Listar usuarios'
        mostrarEnMenu: true

load_ajax_usuario:
    path: /load_ajax
    defaults:
        _controller: ArquitecturaBaseBundle:Usuario:loadAjaxUsuarios

usuario_eliminar:
    path: /eliminar
    defaults:
        _controller: ArquitecturaBaseBundle:Usuario:eliminarUsuario




