#####################   Usuario #######################################################################
usuario_agregar:
    path: /usuario/agregar
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:crearUsuario
        etiqueta: 'Crear un usuario'
        mostrarEnMenu: true

usuario_modificar:
    path: /usuario/modificar/{idusuario}
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:modificarUsuario

usuario_listar:
    path: /usuario/listar
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:listarUsuarios
        etiqueta: 'Listar usuarios'
        mostrarEnMenu: true

load_ajax_usuario:
    path: /usuario/load_ajax
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:loadAjaxUsuarios
#POST
usuario_eliminar:
    path: /usuario/eliminar
    defaults:
        _controller: ArquitecturaBaseBundle:Administracion:eliminarUsuario

#####################   Fin de Usuario #################################################################



